#include "Rules/LintRule_NiagaraSystem_Compiles.h"

#include "NiagaraSystem.h"
#include "ShaderCompilerCore.h"

#define LOCTEXT_NAMESPACE "UE5Linter"

ULintRule_NiagaraSystem_Compiles::ULintRule_NiagaraSystem_Compiles(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	RuleGroup = TEXT("UE5.Niagara");
	RuleTitle = LOCTEXT("NiagaraSystemCompilesTitle", "Niagara systems must compile successfully");
	RuleDescription = LOCTEXT("NiagaraSystemCompilesDescription", "Compiles dirty Niagara system scripts, waits for VM and GPU compilation, and checks Niagara's system validity for the current editor platform and scalability settings. This does not validate standalone emitter assets or every target platform.");
	RuleSeverity = ELintRuleSeverity::Error;
	bRequiresGameThread = true;
}

bool ULintRule_NiagaraSystem_Compiles::PassesRule_Internal_Implementation(UObject* ObjectToLint, const ULintRuleSet* ParentRuleSet, TArray<FLintRuleViolation>& OutRuleViolations) const
{
	UNiagaraSystem* System = Cast<UNiagaraSystem>(ObjectToLint);
	if (System == nullptr)
	{
		return true;
	}

	// Compilation and post-load work access editor UObjects and must run on the game thread.
	if (!IsInGameThread())
	{
		OutRuleViolations.Emplace(ObjectToLint, GetClass(), LOCTEXT("NiagaraWrongThread", "Run this Niagara rule on the game thread. Enable Requires Game Thread on the rule."));
		return false;
	}

	if (!AllowShaderCompiling())
	{
		OutRuleViolations.Emplace(ObjectToLint, GetClass(), LOCTEXT("NiagaraCompilationDisabled", "Niagara compilation cannot be checked while shader compilation is disabled. Run again without NoShaderCompile or PrecompiledShadersOnly."));
		return false;
	}

	System->EnsureFullyLoaded();
	System->RequestCompile(false);
	// UE gathers the GPU jobs before draining VM compilation. Wait for VM results
	// first so the second wait includes shaders generated by those results.
	System->WaitForCompilationComplete(false, false);
	System->WaitForCompilationComplete(true, false);

	if (System->HasOutstandingCompilationRequests(true))
	{
		OutRuleViolations.Emplace(ObjectToLint, GetClass(), LOCTEXT("NiagaraCompilationIncomplete", "Niagara compilation has not completed. Open the system, wait for compilation to finish, and scan again."));
		return false;
	}

	if (!System->IsValid())
	{
		OutRuleViolations.Emplace(ObjectToLint, GetClass(), LOCTEXT("NiagaraInvalidSystem", "Open this Niagara system and resolve its compile errors or invalid system/emitter data. A system must contain an emitter and valid system scripts."));
		return false;
	}

	return true;
}

#undef LOCTEXT_NAMESPACE
